server:
  port: ${PORT:9001}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27018/auth}
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
