server:
  port: ${PORT:9001}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/auth
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}/eureka
app:
  env:
    secret-key: ${SECRET_KEY}
