server:
  port: ${PORT:9001}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/auth
  application:
    name: AUTH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}/eureka

app:
  mqtt:
    broker: broker-from-auth
    username: username-from-auth
    clientId: ${spring.application.name}
    password: password-from-auth
