server:
  port: ${PORT:9001}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}/auth-service
  application:
    name: AUTH-SERVICE

app:
  mqtt:
    broker: ${MQTT_BROKER}
    username: ${MQTT_USERNAME}
    clientId: ${spring.application.name}
    password: ${MQTT_PASSWORD}
  utils:
    auth-service-base-url: http://localhost:${server.port}
    open-api-endpoints:
      - "/auth/login"
      - "/auth/validate"
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:9002}
    user-id-path: /users
